# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 02:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resident_reports', '0003_auto_20170517_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='user_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
